### ISSUE TITLE
redis-cli command error

### ISSUE THREAD

**Issue by wanyxkhalil** [flower-corp/rosedb#80]
redis-cli connection success, but command exec fail. rosedb-cli success.

![image](https://user-images.githubusercontent.com/21099937/147032742-a5f52943-7214-4c44-9f48-ab08041a0e53.png)

![image](https://user-images.githubusercontent.com/21099937/147032933-6a477441-56dd-4de1-a9f2-d1c8854c32e8.png)

![image](https://user-images.githubusercontent.com/21099937/147033244-7d3375aa-b5fe-48c8-b1e1-f4ec25c6707c.png)

redis-cli version: 6.2.6

**Comment by sober-wang** [comment]
I recommend you enter the rosedb/cmd/cli , next run `go run main.go` . 

because, some redis cli command is not unrealized.

**Comment by wanyxkhalil** [comment]
It's `set` command, works in README.md. So, something broken?

**Comment by sober-wang** [comment]
yeh , I remember it. server address defalut is 127.0.0.1:5200 in the config file. if Golang tcp address is 127.0.0.1 , it can't remote visiter.

so , you should edit the config file. the config look like these.
[config_file_address](https://github.com/flower-corp/rosedb/blob/main/config.toml)
```toml
# Default rosedb server address and port.
addr = "127.0.0.1:5200"   # this addr modify to your host ip address and port 
# Default rosedb server gRPC addr and port. 
grpc_addr = "127.0.0.1:5300"

# Default rosedb data dir: /tmp/rosedb.
# Do not use the default path before you use it in production.
dir_path = "/tmp/rosedb"

# DB file read and write method, 0:FileIO 1:MMap.
rw_method = 0

# The index mode, 0: KeyValueMemMode, 1: KeyOnlyMemMode.
idx_mode = 1

# The max size of key: 1MB.
max_key_size = 1048576

# The max size of value: 8MB.
max_value_size = 8388608

# Flush the db file to disk of every write operation.
sync = false

# The threshold for db file reclaiming.
merge_threshold = 64

# The capacity of cache
cache_capacity = 0
```
